services:

  mwbot:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION:-20}
    volumes:
      - ./coverage:/work/coverage

  wiki:
    build:
      context: .
      dockerfile: Dockerfile.wiki
      args:
        MW_VERSION: ${MW_VERSION:-1.43}
        PHP_VERSION: ${PHP_VERSION:-8.2}

  wait-for-wiki:
    image: mintel/docker-wait-for-it
    entrypoint: ['/opt/wait-for-it.sh', 'wiki:8080', '-t', '120']
    profiles:
      - no-up
