ARG MW_VERSION
ARG PHP_VERSION
FROM gesinn/mediawiki-ci:${MW_VERSION}-php${PHP_VERSION}

WORKDIR /var/www/html
RUN sudo -u www-data php maintenance/install.php \
    --pass=wiki4everyone \
    --server="http://wiki" \
    --scriptpath="" \
    --dbtype=sqlite \
    --dbname=wiki \
    --dbuser=wiki \
    --dbpass=wiki \
    --dbpath=/var/www/data \
    wiki WikiSysop && \
    echo '$wgEnableUploads = true;' >> LocalSettings.php
