name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  ci:
    name: "MW ${{ matrix.mw }} / PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - { mw: '1.39', php: '8.1' }
          - { mw: '1.43', php: '8.2', coverage: true }
          - { mw: '1.44', php: '8.3' }
          - { mw: '1.45', php: '8.3' }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CI
        run: MW_VERSION=${{ matrix.mw }} PHP_VERSION=${{ matrix.php }} make ci

      - name: Ensure down
        run: make down
        if: always()

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage/clover.xml
        if: matrix.coverage == true
